package global.ututaxfree.taxfreeandroidui

import java.util.*

/**
 * Created by Likhitha on 20/12/2019
 */
class FriendsList(val index: String, val name: String) {

    companion object {
        @JvmStatic
        val englishContacts: List<FriendsList>
            get() {
                val contacts: MutableList<FriendsList> = ArrayList()
                contacts.add(
                    FriendsList(
                        "A",
                        "Abbey"
                    )
                )
                contacts.add(
                    FriendsList(
                        "A",
                        "Alex"
                    )
                )
                contacts.add(
                    FriendsList(
                        "A",
                        "Amy"
                    )
                )
                contacts.add(
                    FriendsList(
                        "A",
                        "Anne"
                    )
                )
                contacts.add(
                    FriendsList(
                        "B",
                        "Betty"
                    )
                )
                contacts.add(
                    FriendsList(
                        "B",
                        "Bob"
                    )
                )
                contacts.add(
                    FriendsList(
                        "B",
                        "Brian"
                    )
                )
                contacts.add(
                    FriendsList(
                        "C",
                        "Carl"
                    )
                )
                contacts.add(
                    FriendsList(
                        "C",
                        "Candy"
                    )
                )
                contacts.add(
                    FriendsList(
                        "C",
                        "Carlos"
                    )
                )
                contacts.add(
                    FriendsList(
                        "C",
                        "Charles"
                    )
                )
                contacts.add(
                    FriendsList(
                        "C",
                        "Christina"
                    )
                )
                contacts.add(
                    FriendsList(
                        "D",
                        "David"
                    )
                )
                contacts.add(
                    FriendsList(
                        "D",
                        "Daniel"
                    )
                )
                contacts.add(
                    FriendsList(
                        "E",
                        "Elizabeth"
                    )
                )
                contacts.add(
                    FriendsList(
                        "E",
                        "Eric"
                    )
                )
                contacts.add(
                    FriendsList(
                        "E",
                        "Eva"
                    )
                )
                contacts.add(
                    FriendsList(
                        "F",
                        "Frances"
                    )
                )
                contacts.add(
                    FriendsList(
                        "F",
                        "Frank"
                    )
                )
                contacts.add(
                    FriendsList(
                        "G",
                        "Germany"
                    )
                )
                contacts.add(
                    FriendsList(
                        "G",
                        "Greece"
                    )
                )
                contacts.add(
                    FriendsList(
                        "G",
                        "Georgia"
                    )
                )
                contacts.add(
                    FriendsList(
                        "G",
                        "Grenada"
                    )
                )
                contacts.add(
                    FriendsList(
                        "I",
                        "Ivy"
                    )
                )
                contacts.add(
                    FriendsList(
                        "J",
                        "James"
                    )
                )
                contacts.add(
                    FriendsList(
                        "J",
                        "John"
                    )
                )
                contacts.add(
                    FriendsList(
                        "J",
                        "Jessica"
                    )
                )
                contacts.add(
                    FriendsList(
                        "K",
                        "Karen"
                    )
                )
                contacts.add(
                    FriendsList(
                        "K",
                        "Karl"
                    )
                )
                contacts.add(
                    FriendsList(
                        "K",
                        "Kim"
                    )
                )
                contacts.add(
                    FriendsList(
                        "L",
                        "Leon"
                    )
                )
                contacts.add(
                    FriendsList(
                        "L",
                        "Lisa"
                    )
                )
                contacts.add(
                    FriendsList(
                        "P",
                        "Paul"
                    )
                )
                contacts.add(
                    FriendsList(
                        "P",
                        "Peter"
                    )
                )
                contacts.add(
                    FriendsList(
                        "S",
                        "Sarah"
                    )
                )
                contacts.add(
                    FriendsList(
                        "S",
                        "Steven"
                    )
                )
                contacts.add(
                    FriendsList(
                        "R",
                        "Robert"
                    )
                )
                contacts.add(
                    FriendsList(
                        "R",
                        "Ryan"
                    )
                )
                contacts.add(
                    FriendsList(
                        "T",
                        "Tom"
                    )
                )
                contacts.add(
                    FriendsList(
                        "T",
                        "Tony"
                    )
                )
                contacts.add(
                    FriendsList(
                        "W",
                        "Wendy"
                    )
                )
                contacts.add(
                    FriendsList(
                        "W",
                        "Will"
                    )
                )
                contacts.add(
                    FriendsList(
                        "W",
                        "William"
                    )
                )
                contacts.add(
                    FriendsList(
                        "Z",
                        "Zoe"
                    )
                )
                return contacts
            }
    }

}